#!/bin/sh
export WORKSHOP_BACKEND_HOST="0.0.0.0"
export WORKSHOP_BACKEND_PORT="${PORT:-7860}"
export WORKSHOP_BACKEND_ALLOW_ORIGIN="${WORKSHOP_BACKEND_ALLOW_ORIGIN:-*}"
poetry run python -m backend.app
