#!/bin/zsh
export WORKSHOP_BACKEND_HOST="${WORKSHOP_BACKEND_HOST:-0.0.0.0}"
export WORKSHOP_BACKEND_PORT="${WORKSHOP_BACKEND_PORT:-8765}"
export WORKSHOP_BACKEND_ALLOW_ORIGIN="${WORKSHOP_BACKEND_ALLOW_ORIGIN:-*}"
poetry run python -m backend.app
